name: build 11ty site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install

  fetch-issues:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Fetch GitHub Issues
        run: node scripts/fetchIssues.js

  build:
    runs-on: ubuntu-latest
    needs: [setup, fetch-issues]
    steps:
      - name: Build site
        run: npx @11ty/eleventy
      - uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}